name: build
on:
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Populate production .env
        run: |
          touch .env.production
          echo VUE_APP_API_ENDPOINT=${{ secrets.API_ENDPOINT }}  >> .env.production
          echo VUE_APP_I18N_LOCALE=es  >> .env.production
          echo VUE_APP_I18N_FALLBACK_LOCALE=es  >> .env.production
          cat .env.production
      -
        name: Set up development Docker Buildx
        id: development_builder
        uses: docker/setup-buildx-action@v1
      -
        name: Set up production Docker Buildx
        id: production_builder
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push production container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          builder: ${{ steps.production_builder.outputs.name }}
          target: production
          tags: namelivia/gallery-client:latest
